### ISSUE TITLE
Storage optimization in Vat.frob

### ISSUE THREAD

**Issue by kmbarry1** [makerdao/xdomain-dss#3]
At the end of `Vat.frob`, the entire `Ilk` struct is written out to storage, but only `Art` was modified. To reduce storage operations, the code could be modified as follows:

```diff
-        urns[i][u] = urn;
-        ilks[i]    = ilk;
+        urns[i][u]  = urn;
+        ilks[i].Art = ilk.Art;
```

**Comment by gbalabasquer** [comment]
This has been addresses in this PR: https://github.com/makerdao/xdomain-dss/pull/5
